### ISSUE TITLE
Error: Private key must be a 32-byte buffer

### ISSUE THREAD

**Issue by debianmaster** [llSourcell/sirajcoin#17] opened 2018-01-20 16:02 UTC
```sh
$ sirajcoin balance
Generated private key, saving to "/Users/jjonagam/.sirajcoin/keys.json"
Error: Private key must be a 32-byte buffer
    at module.exports (/usr/local/lib/node_modules/sirajcoin/client/wallet-methods.js:7:11)
    at main (/usr/local/lib/node_modules/sirajcoin/bin/wallet.js:58:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
Connecting...
```

$ node --version
v9.4.0

**Comment by aslafy-z** [comment] 2018-01-20 16:13
Duplicate of #4

**Closed** 2018-01-20 17:17 UTC
